##############################
### Package data documentation
###############################
## Roxygen documentation for datasets bundled under data/. The data objects
## themselves are generated by scripts in data-raw/.


#' Labelled test cases for data-type detectors
#'
#' A frozen set of valid and deliberately-corrupted example values for each
#' data type, used to exercise the detectors in the \code{R/dt-<family>.R}
#' files (e.g. \code{R/dt-currency.R}). Negatives are produced by the AutoType
#' mutation strategies (see \code{\link{generate_autotype_test_cases}}) with a
#' fixed seed, so the fixture is reproducible.
#'
#' @format A named list, one element per data type (e.g. `currency_code`). Each
#'   element is a data frame with columns:
#'   \describe{
#'     \item{data_type}{Character. The type name (matches the list element).}
#'     \item{case}{Character. The example value.}
#'     \item{label}{Character. `"valid"` for a real positive, or the mutation
#'       tier that produced a negative: `"S1"` (preserve structure), `"S2"`
#'       (preserve alphabet), `"S3"` (random), or `"SP"` (scramble structure).}
#'   }
#'
#' @source Positive examples seeded from the AutoType benchmark (Yan & He,
#'   SIGMOD 2018), cleaned and expanded; negatives generated by
#'   \code{data-raw/build_test_cases.R}.
#'
#' @seealso \code{\link{generate_autotype_test_cases}}, \code{\link{guess_data_type}}
"data_type_tests"
